---
- hosts: all
  vars:
    users: ['user1', 'user2']
    user_password_valid_time: 30
  tasks:
    - name: check users password valid time
      shell: getent shadow "{{ item }}" | cut -d':' -f5
      register: users_pw_valid
      loop: users
      changed_when: False
      
    - name: set users password valid time
      shell: chage -M "{{ user_password_valid_time }}" "{{ item['item'] }}"
      loop: users_pw_valid.results
      when: item.stdout is defined and item.stdout != {{ user_password_valid_time }}
